#******************************************************
# Generated by Board2Make (github\luni\xxx)
#
# Board              Teensy 3.2 / 3.1
# USB Type           Keyboard
# CPU Speed          72 MHz
# Optimize           Fast
# Keyboard Layout    Canadian French
#
# 26.06.2017 19:09
#******************************************************

BOARD_ID   := TEENSY31

FLAGS_CPU  := -mthumb -mcpu=cortex-m4 -fsingle-precision-constant
FLAGS_OPT  := -O1
FLAGS_COM  := -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD
FLAGS_LSP  := 

FLAGS_CPP  := -fno-exceptions -felide-constructors -std=gnu++0x -fno-rtti
FLAGS_C    := 
FLAGS_S    := -x assembler-with-cpp
FLAGS_LD   := -Wl,--gc-sections,--relax,--defsym=__rtc_localtime=0

LIBS       := -larm_cortexM4l_math -lm
LD_SCRIPT  := mk20dx256.ld

DEFINES    := -D__MK20DX256__ -DTEENSYDUINO=136
DEFINES    += -DF_CPU=72000000 -DUSB_KEYBOARDONLY -DLAYOUT_CANADIAN_FRENCH

CPP_FLAGS  := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_CPP)
C_FLAGS    := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_C)
S_FLAGS    := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_S)
LD_FLAGS   := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_LSP) $(FLAGS_LD)
AR_FLAGS   := rcs
